#!/usr/bin/env python

import os
from time import sleep

from curator.config import get
from curator.indicator import main as gui_main
from curator.service import main as backend_main

if __name__=='__main__':
    try:
        pid = os.fork()
        if pid == 0:
            sleep(5)
            gui_main()
        else:
            backend_main()
    except IOError:
        pass
