#!/usr/bin/env python

import subprocess
from time import sleep

from curator.indicator import main as gui_main

if __name__=='__main__':
    backend = subprocess.Popen("curator-dbus")
    sleep(2)
    if not backend.poll():
        gui_main()
    else:
        print "Failed to start backend!"
