.TH CURATOR-DBUS 1 "May 2, 2011" "" ""
.SH NAME
curator-dbus \- D-Bus backend for the curator desktop wallpaper switcher
.SH SYNOPSIS
.B curator-dbus
.SH DESCRIPTION
.B curator-dbus
is a simple backend which listens over D-Bus and sets the desktop background
at configurable intervals. You should not run this directly; instead, run
.B curator
which calls 
.B curator-dbus.
.SH "AUTHORS"
.B curator
was written by Michael Moorman, 2011
.SH "SEE ALSO"
curator(1)
