.TH CURATOR 1 "May 2, 2011" "" ""
.SH NAME
curator \- GNOME background-switching application
.SH SYNOPSIS
.B curator
.SH DESCRIPTION
.B curator
is a simplistic GNOME indicator application for controlling your desktop 
wallpaper. It keeps track of liked and disliked wallpapers and has configurable
settings for updates and notifications. It is also controllable over D-Bus.
.SH "AUTHORS"
.B curator
was written by Michael Moorman, 2011
.SH "SEE ALSO"
curator-dbus(1)
